# Generated by Django 3.2.20 on 2023-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_g1aaa6.jpg', upload_to='images/'),
        ),
    ]
